//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 13/06/2018 17:33:10
namespace Lezione4
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Lezione4.wgame </summary>
        public const string GameInfo = "Content/Lezione4.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/ball.png </summary>
            public const string ball_png = "Content/Assets/ball.png";
            
            /// <summary> Path to Content/Assets/field.png </summary>
            public const string field_png = "Content/Assets/field.png";
            
            /// <summary> Path to Content/Assets/SpriteSheet.spritesheet </summary>
            public const string SpriteSheet_spritesheet = "Content/Assets/SpriteSheet.spritesheet";
            
            /// <summary> Path to Content/Assets/tree2.png </summary>
            public const string tree2_png = "Content/Assets/tree2.png";
            
            /// <summary> Texture names from spritesheet Content/Assets/SpriteSheet.spritesheet </summary>
            public struct SpriteSheet_spritesheet_TextureName
            {
                
                public const string GameBackground = "GameBackground";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
